### PR TITLE
Created output_html.py. Added output html option to __main__.py.

### PR DESCRIPTION
**Pull request by ddfault**
Created pyflowchart/output_html.py to store three variables used writing output html file. 
Modified pyflowchart/__main__.py to import these three variable and import os. 
import os is needed to convert a path to the output file into a output filename used as the header in the output html file. 
This is a very basic output entirely based on example.html from [github flowchart.js example](https://github.com/adrai/flowchart.js/blob/master/example/index.html) and [flowchart.js.org](http://flowchart.js.org/) . I added a helper button with hidden default text based on helper text from flowchart.js.org for tweaking the output html file for live and or saved changes.

### CODE REVIEW

**Review by cdfmlr — CHANGES_REQUESTED** [review]
Thanks a lot for your contribution. 🥳

However, I am afraid that I won't approve merging this branch until following points are addressed.

Functionally, you code looks great. The data flow is all right. The problem is the readability. 

1. I am confused by the `html_part_1/2/3`. Variables' name should be meaningful.
2. The hardcoded HTML contents are hardly readable as well as maintainable. I suggest making it a separated template file. And inject the `flowchart.flowchart()` into the template at runtime. Python's [str.format](https://docs.python.org/3.10/library/stdtypes.html#str.format) or [template strings](https://docs.python.org/3.10/library/string.html#template-strings) may be helpful.

**Comment by ddfault** [comment]
Hi so, 
I've revised variable names and figured out I can use """ to block quote raw html. So replaced string I had read in with python to get it formatted safe to this version. I added more comments on what I'm trying to do in both main and in this output_html.py python file. Does that resolved your concerns?

**Review by cdfmlr — COMMENTED** [review]
Thank you for your efforts again. It looks much better now. 👏

However, forgive my rigorous, in my perspective, it can be even better if we can move the code of writing output file into a separate function in the `output_html.py`, for example an `output_html(file_name: str) -> None`, and then call it in the `main()` function. 

It will help to keep the `main()` as simple as possible. And it also makes the future revise of the `output_html` implementation easier and transparent for `main()`. 

How do you feel about this approach?

Btw, I couldn't quite understand the print statement at `__main__.py` L86. 😂

**Comment by ddfault** [comment]
Thanks for the example. I'm fine moving it all into separate python file. reason i get variables in separate file is I didn't want to add a lot to main.py. function probably like
output_html(file_name: str, html_title: str, flowchart: str)

In main how do you feel about
if bool(output):
	if bool(field):
		f.write(field)
		output_html(file_name=output, html_title=field, flowchart=flowchart.flowchart())
	else:
		f.write()
		output_html(file_name=output, html_title=os.path.basename(f.name), flowchart=flowchart.flowchart())

**Comment by ddfault** [comment]
Tried to amend a typo in commit comment and ended up where my branch is now. But otherwise, I've implemented as we discussed last night.

**Review by cdfmlr — COMMENTED** [review]
A little 🐛.

**Comment by cdfmlr** [comment]
> A little 🐛.

I have resolved it.

**Comment by ddfault** [comment]
Should we have
`with open(os.path.expanduser(output_name), 'w') as f:`
instead of
`with open(output_name, 'w') as f:`
?

**Comment by cdfmlr** [comment]
> Should we have
> `with open(os.path.expanduser(output_name), 'w') as f:`
> instead of
> `with open(output_name, 'w') as f:`
> or even
> `with open(os.path.expandvars(os.path.expanduser(output_name)), 'w') as f:`
> ?

Yes. While I am not used to write this, it's not hurt anyway. (Btw is this a common pattern? I didn't see this often.)

---

What I am concerned now is that we'd better check the suffix of `file_name` first. In case that users entering commands with `-o notsupported.png`, which may cause misunderstanding. We should only accept the `.html` suffix. How do you like this?

**Comment by ddfault** [comment]
It broken into separate sections. As I've written it, if user does something convoluted it'll render a bad path. 
i.e. ~\%username%\ will give the same bad result with 
os.path.expandvars(os.path.expanduser('~\%USERNAME%')) or
os.path.expanduser(os.path.expandvars('~\%USERNAME%'))
as the expansions are mutually exclusive. but combining will give you correct results for ~\file.bob ~/file.bob %temp%\file.bob %temp%/file.bob
pallet's click handles it this way:
https://github.com/pallets/click/blob/388b0e14093355e30b17ffaff0c7588533d9dbc8/src/click/utils.py#L575-L624
  ```
  for arg in args:
        if user:
            arg = os.path.expanduser(arg)


        if env:
            arg = os.path.expandvars(arg)
```

**Comment by cdfmlr** [comment]
> html or htm sounds fine to me we can append if they don't include that suffix. We can output a warning if they didn't provide letting them know we changed suffix. Would you like me to implement?

I have written lines of code for this (but not completed). Would you mind it if I implement this feature and push it to your branch?

> Looking at click the handling of args is broken into separate sections. As I've written it, if user does something broken it'll render a bad path. i.e. `~\%username%\` will give the same bad result with `os.path.expandvars(os.path.expanduser('~\%USERNAME%'))` or `os.path.expanduser(os.path.expandvars('~\%USERNAME%'))`
> 
> The two expansions are mutually exclusive. Combining will give you correct results for ~\file.bob ~/file.bob %temp%\file.bob %temp%/file.bob or %userprofile%/file.bob as some examples. pallet's click handles it this way: https://github.com/pallets/click/blob/388b0e14093355e30b17ffaff0c7588533d9dbc8/src/click/utils.py#L575-L624
> 
> ```
> for arg in args:
>       if user:
>           arg = os.path.expanduser(arg)
> 
> 
>       if env:
>           arg = os.path.expandvars(arg)
> ```

Understood. Thanks for the explanation.

**Comment by cdfmlr** [comment]
> html or htm sounds fine to me we can append if they don't include that suffix. We can output a warning if they didn't provide letting them know we changed suffix. Would you like me to implement?

I implemented it in https://github.com/ddfault/pyflowchart/commit/56bf90bb4bdb99ea40cdb5346dd1b95fbfb7baa1. Err, I am sleepy and not sure if I made it correctly. Please review it.

**Comment by ddfault** [comment]
My gripes are we don't append the extension we need, don't tell them it needs to end in a specific extension, and don't output to screen given a bad -o string
py -m pyflowchart %path%\code.py -f bob -o code.bob only gets me
Error: not supported output file format:', code.bob
I'm not telling them in the helper text
 parser.add_argument('-o', '--output', default="", type=str, help="Output HTML file with flowchart")
 that they need to specifcy .html or .htm 
I would rather just append the .htm or html for them in this case. We could check for known image types and then error out. 
or
print(f'\n*** Error: {ext} not supported output file format:', file_name)  # TODO: stderr
print(f'\n*** Error: {ext} not supported output file format. Currently only .htm or .html supported:', file_name)  # TODO: stderr
something along those lines is what I can think of atm.

**Comment by cdfmlr** [comment]
> My gripes are we don't append the extension we need, don't tell them it needs to end in a specific extension, and don't output to screen given a bad -o string
> py -m pyflowchart %path%\code.py -f bob -o code.bob only gets me
> Error: not supported output file format:', code.bob
> I'm not telling them in the helper text
> parser.add_argument('-o', '--output', default="", type=str, help="Output HTML file with flowchart")
> that they need to specifcy .html or .htm
> I would rather just append the .htm or html for them in this case. We could check for known image types and then error out.
> or
> print(f'\n*** Error: {ext} not supported output file format:', file_name) # TODO: stderr
> print(f'\n*** Error: {ext} not supported output file format. Currently only .htm or .html supported:', file_name) # TODO: stderr
> something along those lines is what I can think of atm.
> 
I see. However I’m a bit disagree with your idea of appending an extension to the file name automatically. 

As an UNIX user, I would not be happy to see a program writing to a file whose name is not explicitly mentioned by me.. I don’t know how to explain this. I just feel this behavior is not in common. “I commanded you to write a file called foo, but you wrote to the foo.html” this is a bit strange. It makes me feel like I’m losing my control of the computer. 

My point is that I implemented the output function in a way that supports any format that might be implemented in the future. 

In this case, the original print(flowchart) and our new output_html() are becoming two of the possible formats that we support, though they are the only two formats that are available now.

So maybe an amendment to the help str of -o could explain my design clearer: “Output the flowchart to specific file with a format indicating by the extension name.”

How do you think?

**Comment by ddfault** [comment]
I edited again after what your comment shows as your email. Sorry I keep editing my comments :/ 
Your approach is probably the simplest and gets the point across (versus appending and checking for known image extensions) not outputting to console on error just requires them tot run again which isn't a big deal so probably right move.
I'd still would like the error to say something along the lines of:
`print(f'\n*** Error: {ext} not supported output file format. Currently only .htm or .html supported:', file_name)  # TODO: stderr`

Also by the way... I just pushed HTML changes. You can now open the html and download the rendered flowchart as png or svg. My flowcharts always need a bit of tweaking no,left yes,right etc before they look clean. The download links update when you click run and generate a new canvas.

**Comment by cdfmlr** [comment]
Downloading the image is super useful! (Btw I know a package that may make this easier: https://www.npmjs.com/package/html-to-image)

And I amended the help str of -o as well as the error message as discussed above.

I feel it's time to merge this PR. Thanks for all of your contribution.

Would you find anything to be done before we merge it?

**Comment by ddfault** [comment]
Sure. I'll take a look at revising the readme tomorrow and then you can revise from there.

**Comment by ddfault** [comment]
I've pushed README.md changes. Please review and revise as you see fit.

**Comment by cdfmlr** [comment]
> I've pushed README.md changes. Please review and revise as you see fit. I haven't updated the TODO section or the non-english README.md

okk, thanks

**Comment by cdfmlr** [comment]
I made some change on both code & docs:

- export the `output_html` function and move your file doc of `output_html.py` as `output_html()`'s function doc to support:

```py
>>> from pyflowchart import output_html
>>> help(output_html)
```

- refactor the document about output html.

Any comments or suggestions?

**Review by cdfmlr — APPROVED** [review]

**Comment by cdfmlr** [comment]
Thanks for your contributions, @ddfault! I'm merging this now. Please feel free to continue improving it in the future.

**Pull request merged**
